blank_issues_enabled: false
contact_links:
  - name:  Descargar Juego
    url: https://github.com/Kavalieri/SiK-Python-Game/releases/latest
    about: Descarga la 煤ltima versi贸n del juego
  - name:  Documentaci贸n
    url: https://github.com/Kavalieri/SiK-Python-Game/blob/main/docs/README.md
    about: Consulta la documentaci贸n t茅cnica completa
  - name:  Gu铆a de Contribuci贸n
    url: https://github.com/Kavalieri/SiK-Python-Game/blob/main/CONTRIBUTING.md
    about: Aprende c贸mo contribuir al proyecto
